<?php

/**
 * @file
 * Crosscut Logger module file.
 */

/**
 * Implements hook_mail().
 */
function crosscut_logger_mail($key, &$message, $params) {
  switch ($key) {
    case 'log_notification':
      $message['subject'] = t('Log notification: @site', [
        '@site' => \Drupal::request()->getHost(),
      ]);

      $message['body'][] = $params['message'];
      foreach ($params['context'] as $key => $param) {
        $message['body'][] = sprintf("%s: %s", $key, $param);
      }

      break;
  }
}
